<a href="https://colab.research.google.com/github/monishvarghesejoshy/emanzon/blob/adf_publish/try.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
p=10
q=4
z=p/q
print (z)

2.5


In [ ]:
input1=int(input("enter first digit"))

match input1:
    case 1:
        print("one")
    case 2:
        print("two")
    case 3:
        print("three")
    case 4:
        print("four")
    case 5:
        print("five")
    case _ :
        print("invalid")


enter first digit8
invalid


In [ ]:
a=[1,2,3,4,5]
for i in a:
    if i%2==1:
        print(i ,"is odd")
    else:
        print(i, "is even")

1 is odd
2 is even
3 is odd
4 is even
5 is odd


In [ ]:
for i in range(2,30,1):
  for j in range(2,i):
     if (i%j) == 0:
      print(i, "is not a prime")
      break
  else:
    print(i, "is a prime")


2 is a prime
3 is a prime
4 is not a prime
5 is a prime
6 is not a prime
7 is a prime
8 is not a prime
9 is not a prime
10 is not a prime
11 is a prime
12 is not a prime
13 is a prime
14 is not a prime
15 is not a prime
16 is not a prime
17 is a prime
18 is not a prime
19 is a prime
20 is not a prime
21 is not a prime
22 is not a prime
23 is a prime
24 is not a prime
25 is not a prime
26 is not a prime
27 is not a prime
28 is not a prime
29 is a prime


In [ ]:
x=1
while x<7:

  print (x)

  x+=1


1
2
3
4
5
6


In [ ]:
def ab(x):
     if ( x <0):
        y= x*-1
     else:
       y=x
     return(y)
ab(7)



7

In [ ]:
def sum(n):
  result=0
  for i in range(1, n+1):
        result=result+i
        i=i+1
  return(result)
sum(6)

21

In [ ]:
name='Jacob'
'a' in name

True

In [ ]:
word = '''God
is Love'''
"Love" in word

True

In [ ]:
st=''' Work Hard and Work Smart'''
for c in st:
     print( c)

 
W
o
r
k
 
H
a
r
d
 
a
n
d
 
W
o
r
k
 
S
m
a
r
t


In [ ]:
s1="Hello "
s2=s1.strip()
s2

'Hello'

In [ ]:
s1.replace("He","ha")

'hallo '

In [1]:
dict1={'Name': 'Monish', 'Age':41, 'Gender':'Male'}
dict1

{'Name': 'Monish', 'Age': 41, 'Gender': 'Male'}

In [2]:
dict1.keys()

dict_keys(['Name', 'Age', 'Gender'])

In [3]:
dict1.values()

dict_values(['Monish', 41, 'Male'])

In [5]:
dict1.items()

dict_items([('Name', 'Monish'), ('Age', 41), ('Gender', 'Male')])

In [13]:

dict1.items()
del dict1['Age']
dict1

{'Name': 'Monish'}

In [14]:
dict1.clear()
dict1

{}

In [17]:
num=int(input('Enter the number of Employees'))
count=1
employee=dict()
while count<= num:
  name=input('Enter the name')
  salary=int(input('Enter the salary'))
  employee[name]=salary
  count+=1
for name,salary in employee.items():
  print(name,salary)


Enter the number of Employees2
Enter the namejosh
Enter the salary5000
Enter the namedan
Enter the salary4000
josh 5000
dan 4000


In [4]:
import  numpy as np
x=np.array([1,2,3])
x
type(x)
y=np.ones((2,2), dtype=np.int16)
y

array([[1, 1],
       [1, 1]], dtype=int16)

In [5]:
x=np.arange(10,80,5)
x

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [7]:
y=np.linspace(0,1/4,3)
y

array([0.   , 0.125, 0.25 ])

In [8]:
i=np.random.rand(3,4)
i

array([[0.23787674, 0.86355945, 0.8593668 , 0.23837462],
       [0.78613028, 0.63356274, 0.22264688, 0.84030964],
       [0.47084623, 0.57269373, 0.67461817, 0.46024784]])

In [11]:
j=np.empty((3,4), dtype=np.int16)

j

array([[    0,     0,     0,     0],
       [    0,     0,     0, 16320],
       [    0,     0,     0, 16336]], dtype=int16)